<a href="https://colab.research.google.com/github/Olamyyde/test-colab/blob/master/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 51](#1)
* [Exercise 52](#2)
* [Exercise 53](#3)
* [Exercise 54](#4)
* [Exercise 55](#5)
* [Exercise 56](#6)
* [Exercise 57](#7)
* [Exercise 58](#8)
* [Exercise 59](#9)
* [Exercise 60](#10)

### <a name='0'></a> Import of libraries

In [1]:
import numpy as np

np.__version__

'1.18.5'

### <a name='1'></a> Exercise 51
Two arrays $ A $ and $ B $ are given below:

```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Concatenate these arrays as follows:

```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```

__Tip:__ Use the _np.concatenate()_ function.

In [10]:
np.concatenate?

In [3]:
# enter solution here
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate((A, B), axis=0)

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Concatenate these arrays as follows:

```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Tip:__ Use the _np.concatenate()_ function.

In [4]:
# enter solution here
np.concatenate((A, B), axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Exercise 52
The first array is given containing the data (_data_) and the second array containing the target class (_target_) for the given row:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```

Concatenate these arrays into one as shown below:

```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```

In [6]:
# enter solution here
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

np.concatenate((data, target), axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Exercise 53
The following three one-dimensional arrays are given:
```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Transform each of these arrays into a column and concatenate them into one large array.

__Expected result:__
```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```
__Tip:__ Use the function _np.column_stack()_.


In [8]:
# enter solution here
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

np.column_stack((feature1,feature2,feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Exercise 54
The following two-dimensional array is given:
```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```
Split an array into three parts so that the first two columns formed the first array $ A1 $, four consecutive second array $ A2 $ and the last two third array $ A3 $.

__Tip:__ Use the function _np.split()_.

In [16]:
# enter solution here
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

A1, A2, A3 = np.split(A, [2,6], axis=1)
print(A1)
print(A2)
print(A3)



[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[2 4 1 2]
 [2 1 2 1]
 [2 0 2 5]
 [0 6 4 1]
 [0 5 3 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Exercise 55
The following numpy array $ A $ is given:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```

Calculate the total number of non-zero elements for this array.

__Tip:__ Use the function _np.count_nonzero()_.


In [18]:
# enter solution here
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A)

32

Calculate the total number of non-zero elements for each row in this array.

__Tip:__ Use the function _np.count_nonzero()_.

In [20]:
# enter solution here
np.count_nonzero(A, axis=1)

array([4, 5, 6, 2, 3, 1, 3, 2, 2, 4])

### <a name='6'></a> Exercise 56
An example numpy array $ A $ is given below:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```

Set the numpy library option to print arrays with specified precision. Set its value to 4 and print the $ A $ array.

In [24]:
# enter solution here
A = np.random.randn(10, 4)

np.set_printoptions(precision=4)
A

array([[-0.3408,  0.0712, -1.5934, -0.3961],
       [-1.0331, -0.4296,  0.113 ,  0.7724],
       [-0.9177, -0.1259, -0.9416, -1.1643],
       [-1.0539,  0.69  , -0.2474, -1.1323],
       [ 1.3721, -1.2632,  1.173 , -0.6647],
       [ 0.6198, -0.322 , -0.8006, -0.4681],
       [-0.7205,  0.4334, -0.0085, -0.0776],
       [ 1.6371,  2.6155,  0.4219,  2.7172],
       [-0.1729,  0.5201, -1.2819, -0.5634],
       [-0.028 , -2.1517, -1.414 ,  0.1656]])

### <a name='7'></a> Exercise 57

The following numpy array $ A $ is given:

```
A = np.array([1.2e-6, 1.7e-7])
```
Set the precision value to 8. Then set the appropriate numpy library option to suppress mathematical notation. Print the array $ A $.

__Expected result:__
```
array([0.0000012 , 0.00000017])
```


In [27]:
# enter solution here
A = np.array([1.2e-6, 1.7e-7])

np.set_printoptions(suppress=True, precision=8)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Exercise 58
The following numpy array $ A $ is given:
```
A = np.random.randn(8, 4)
```
Remove the third column from the $ A $ array.

__Expected result:__
```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Tip:__ Use the _np.delete()_ function.


In [29]:
# enter solution here
A = np.random.randn(8, 4)

np.delete(A, [2], axis=1 )

array([[-0.57614254, -0.4314463 , -0.22464862],
       [ 0.81656477,  0.30873686, -1.17627276],
       [-1.72631748,  0.04843699, -0.7889887 ],
       [ 0.9167841 ,  1.11627464, -2.0239267 ],
       [ 1.17526038,  0.2831823 ,  1.52378509],
       [ 1.50045068, -0.6302375 ,  2.03853976],
       [-0.11359964,  0.0604407 , -0.66110771],
       [-1.11140403, -1.02627358,  0.79002786]])

### <a name='9'></a> Exercise 59

A one-dimensional array $ v $ (vector) is given:

```
v = np.array([3, 4, -2])
```
Calculate the norm of the vetor $ v $.


In [30]:
# enter solution here
v = np.array([3, 4, -2])

np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Exercise 60
An example $ A $ array is given below:

```
A = np.random.randint(10, size=(100, 30))
```
Set the numpy library option to print 10 edge elements. Print the array $ A $.


In [31]:
# enter solution here
A = np.random.randint(10, size=(100, 30))

np.set_printoptions(edgeitems=10)
A

array([[0, 7, 4, 5, 7, 0, 3, 9, 2, 6, ..., 9, 3, 0, 9, 7, 3, 0, 5, 2, 1],
       [9, 4, 8, 1, 8, 1, 2, 6, 3, 7, ..., 6, 8, 3, 7, 2, 0, 0, 9, 4, 5],
       [5, 8, 4, 6, 7, 5, 5, 1, 9, 1, ..., 0, 1, 0, 6, 8, 1, 7, 7, 0, 5],
       [7, 6, 5, 0, 4, 5, 9, 1, 9, 4, ..., 8, 0, 0, 9, 4, 5, 0, 1, 0, 6],
       [8, 1, 7, 4, 4, 6, 1, 0, 2, 7, ..., 8, 7, 5, 5, 5, 0, 0, 4, 0, 8],
       [0, 8, 6, 6, 2, 0, 3, 3, 5, 8, ..., 4, 9, 4, 0, 2, 9, 0, 8, 3, 9],
       [5, 3, 0, 6, 9, 0, 2, 0, 6, 8, ..., 6, 4, 3, 5, 8, 8, 2, 7, 9, 7],
       [7, 8, 7, 4, 4, 5, 5, 8, 7, 2, ..., 2, 0, 5, 4, 0, 9, 5, 6, 0, 0],
       [8, 8, 2, 1, 2, 1, 7, 9, 9, 4, ..., 9, 9, 2, 8, 0, 7, 7, 1, 2, 4],
       [1, 2, 4, 5, 7, 3, 4, 4, 4, 6, ..., 2, 1, 0, 8, 5, 9, 5, 1, 4, 2],
       ...,
       [3, 9, 2, 4, 5, 4, 9, 9, 7, 9, ..., 2, 7, 9, 9, 5, 7, 3, 8, 2, 4],
       [9, 9, 8, 5, 2, 3, 7, 5, 0, 9, ..., 4, 7, 7, 8, 3, 6, 5, 3, 2, 4],
       [1, 7, 4, 3, 2, 8, 8, 9, 7, 6, ..., 0, 3, 2, 0, 1, 6, 0, 6, 3, 7],
       [6, 9, 4, 0, 0, 9, 