<a href="https://colab.research.google.com/github/Olamyyde/test-colab/blob/master/091_100_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 91](#1)
* [Exercise 92](#2)
* [Exercise 93](#3)
* [Exercise 94](#4)
* [Exercise 95](#5)
* [Exercise 96](#6)
* [Exercise 97](#7)
* [Exercise 98](#8)
* [Exercise 99](#9)
* [Exercise 100](#10)

### <a name='0'></a> Import of libraries

In [1]:
import numpy as np
 
np.set_printoptions(linewidth=160, suppress=True)
np.__version__

'1.18.5'

### <a name='1'></a> Exercise 91
The following string _wig_games_raw_ is provided containing data on the WIG.GAMES sector index:

```
wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""
```
Build a numpy array from this data and name it _wig_games_.

__Expected result:__
```
array([['Profil', 'Czas', 'Kurs', 'Zmiana', 'Zmiana%', 'Odn.', 'Otw.', 'Min.', 'Max.', 'Wolumen', 'Obrót', 'Udział'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')
```


In [2]:
wig_games_raw = """Profile  Time    Course  Change  Change% Ref.    Open    Low High    Volume  Turn    Share
11B (11BIT) 17 kwi 17:01    391.00  +8.00   (+2.09%)    383.00  383.50  383.00  394.00  12 784  4 994 874   19.034%
CDR (CDPROJEKT) 17 kwi 17:01    339.50  +5.30   (+1.59%)    334.20  338.30  337.00  344.20  233 059 79 245 368  39.618%
CIG (CIGAMES)   17 kwi 17:03    0.742   -0.012  (-1.59%)    0.754   0.772   0.730   0.772   1 311 078   971 459 1.855%
PLW (PLAYWAY)   17 kwi 17:03    387.50  +18.00  (+4.87%)    369.50  374.00  373.00  388.00  33 206  12 661 786  10.638%
TEN (TSGAMES)   17 kwi 17:02    349.50  +22.50  (+6.88%)    327.00  332.00  330.00  353.50  39 793  13 697 060  28.855%"""
 
# enter solution here
Lines = wig_games_raw.splitlines()
Lines = [line.split('\t') for line in Lines] 
 
wig_games = np.array(Lines, dtype=np.str)

wig_games

array([['Profile  Time    Course  Change  Change% Ref.    Open    Low High    Volume  Turn    Share'],
       ['11B (11BIT) 17 kwi 17:01    391.00  +8.00   (+2.09%)    383.00  383.50  383.00  394.00  12 784  4 994 874   19.034%'],
       ['CDR (CDPROJEKT) 17 kwi 17:01    339.50  +5.30   (+1.59%)    334.20  338.30  337.00  344.20  233 059 79 245 368  39.618%'],
       ['CIG (CIGAMES)   17 kwi 17:03    0.742   -0.012  (-1.59%)    0.754   0.772   0.730   0.772   1 311 078   971 459 1.855%'],
       ['PLW (PLAYWAY)   17 kwi 17:03    387.50  +18.00  (+4.87%)    369.50  374.00  373.00  388.00  33 206  12 661 786  10.638%'],
       ['TEN (TSGAMES)   17 kwi 17:02    349.50  +22.50  (+6.88%)    327.00  332.00  330.00  353.50  39 793  13 697 060  28.855%']], dtype='<U119')

### <a name='2'></a> Exercise 92
Remove the columns from the _wig_games_ array from the previous exercise:
* Change
* Change%
* Ref.
* Volume

__Expected result:__
```
array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']], dtype='<U14')
```


In [3]:
# enter solution here
wig_games = np.delete(wig_games, [3, 4, 5, 9], axis=1)
wig_games


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  


array([['Profile  Time    Course  Change  Change% Ref.    Open    Low High    Volume  Turn    Share'],
       ['11B (11BIT) 17 kwi 17:01    391.00  +8.00   (+2.09%)    383.00  383.50  383.00  394.00  12 784  4 994 874   19.034%'],
       ['CDR (CDPROJEKT) 17 kwi 17:01    339.50  +5.30   (+1.59%)    334.20  338.30  337.00  344.20  233 059 79 245 368  39.618%'],
       ['CIG (CIGAMES)   17 kwi 17:03    0.742   -0.012  (-1.59%)    0.754   0.772   0.730   0.772   1 311 078   971 459 1.855%'],
       ['PLW (PLAYWAY)   17 kwi 17:03    387.50  +18.00  (+4.87%)    369.50  374.00  373.00  388.00  33 206  12 661 786  10.638%'],
       ['TEN (TSGAMES)   17 kwi 17:02    349.50  +22.50  (+6.88%)    327.00  332.00  330.00  353.50  39 793  13 697 060  28.855%']], dtype='<U119')

### <a name='3'></a> Exercise 93
Save the array _wig_games_ from the previous exercise to the _wig_games.csv_ file.

In [4]:
# enter solution here
np.savetxt('wig_games.csv', X=wig_games, fmt='%s', delimiter=',')

Run the cell below to check.

In [5]:
!head wig_games.csv


Profile  Time    Course  Change  Change% Ref.    Open    Low High    Volume  Turn    Share
11B (11BIT) 17 kwi 17:01    391.00  +8.00   (+2.09%)    383.00  383.50  383.00  394.00  12 784  4 994 874   19.034%
CDR (CDPROJEKT) 17 kwi 17:01    339.50  +5.30   (+1.59%)    334.20  338.30  337.00  344.20  233 059 79 245 368  39.618%
CIG (CIGAMES)   17 kwi 17:03    0.742   -0.012  (-1.59%)    0.754   0.772   0.730   0.772   1 311 078   971 459 1.855%
PLW (PLAYWAY)   17 kwi 17:03    387.50  +18.00  (+4.87%)    369.50  374.00  373.00  388.00  33 206  12 661 786  10.638%
TEN (TSGAMES)   17 kwi 17:02    349.50  +22.50  (+6.88%)    327.00  332.00  330.00  353.50  39 793  13 697 060  28.855%


### <a name='4'></a> Exercise 94
Load the contents of the _wig_games.csv_ file into the _wig_games_new_ variable.

In [6]:
# enter solution here
wig_games_raw = np.loadtxt('wig_games.csv', delimiter=',', dtype='str')
wig_games_raw

array(['Profile  Time    Course  Change  Change% Ref.    Open    Low High    Volume  Turn    Share',
       '11B (11BIT) 17 kwi 17:01    391.00  +8.00   (+2.09%)    383.00  383.50  383.00  394.00  12 784  4 994 874   19.034%',
       'CDR (CDPROJEKT) 17 kwi 17:01    339.50  +5.30   (+1.59%)    334.20  338.30  337.00  344.20  233 059 79 245 368  39.618%',
       'CIG (CIGAMES)   17 kwi 17:03    0.742   -0.012  (-1.59%)    0.754   0.772   0.730   0.772   1 311 078   971 459 1.855%',
       'PLW (PLAYWAY)   17 kwi 17:03    387.50  +18.00  (+4.87%)    369.50  374.00  373.00  388.00  33 206  12 661 786  10.638%',
       'TEN (TSGAMES)   17 kwi 17:02    349.50  +22.50  (+6.88%)    327.00  332.00  330.00  353.50  39 793  13 697 060  28.855%'], dtype='<U119')

### <a name='5'></a> Exercise 95
The following string _playway_raw_ is provided containing Playway's March 2020 listings:

```
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""
```

Create an array named _playway_ and assign the following data to it.

In [13]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""

# enter solution here
Lines = playway_raw.splitlines()
Lines = [line.split(',') for line in Lines] 
 
playway = np.array(Lines, dtype=np.str)
playway

array([['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
       ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
       ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
       ['2020-03-04', '324', '340.5', '315', '330', '36152'],
       ['2020-03-05', '344', '344', '310', '315', '35992'],
       ['2020-03-06', '306.5', '307', '291', '305', '32539'],
       ['2020-03-09', '274', '291', '250', '258', '79402'],
       ['2020-03-10', '278', '284.5', '256', '264', '35700'],
       ['2020-03-11', '270', '270', '238.5', '245', '60445'],
       ['2020-03-12', '218', '228', '196', '197', '94031'],
       ['2020-03-13', '210', '229', '198.8', '211', '100412'],
       ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
       ['2020-03-17', '245', '269', '232.5', '264', '99480'],
       ['2020-03-18', '264', '280', '251', '270', '70136'],
       ['2020-03-19', '267', '280', '267', '279.5', '30732'],
       ['2020-03-20', '297.5', '307', '280', '280.5', '43426'],
       [

Delete the column named 'Date'. Assign only column values without headers to the _playway_values_ variable. Convert the array to the _float_ data type.

__Expected result:__
```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])
```

In [14]:
# enter solution here
playway=np.delete(playway, [0], axis=1)
playway_values=playway[1:].astype(float)
playway_values

array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. 

### <a name='6'></a> Exercise 96
For the _playway_values_ array from the previous exercise, calculate the average value for each column. Round the result to two decimal places.

In [15]:
# enter solution here
np.round(playway_values.mean(axis=0), 2)

array([  283.14,   295.25,   268.69,   282.3 , 48688.05])

For the _playway_values_ array from the previous exercise, calculate the minimum value for each column. Round the result to two decimal places.

In [16]:
# enter solution here
np.round(playway_values.min(axis=0), 2)

array([  205.,   228.,   196.,   197., 10316.])

For the _playway_values_ array from the previous exercise, calculate the maximum value for each column. Round the result to two decimal places.

In [17]:
# enter solution here
np.round(playway_values.max(axis=0), 2)

array([   344. ,    344. ,    320. ,    340.5, 100412. ])

Calculate the difference between the maximum and minimum value for each column.

In [18]:
# enter solution here
playway_values.max(axis=0) - playway_values.min(axis=0)

array([  139. ,   116. ,   124. ,   143.5, 90096. ])

### <a name='7'></a> Exercise 97
Using the _playway_values_ array, calculate the new column: the difference between the highest and lowest price.

Steps:
1. assign the calculated difference to the _max_min_diff_ variable
2. add the calculated column (variable _max_min_diff_) to the array _playway_values_ at the end.

__Expected result:__
```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
```

In [22]:
# enter solution here
max_min_diff = playway_values[:, [1]] - playway_values[:, [2]]
playway_values = np.concatenate((playway_values, max_min_diff), axis=1)
playway_values

array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280

### <a name='8'></a> Exercise 98
Extract rows from the array _playway_values_ where closing price is grater than 300.00.

In [23]:
# enter solution here
playway_values[playway_values[:, 3] > 300.0]

array([[  305. ,   324.5,   283.5,   310. , 64081. ,    41. ],
       [  325.5,   340.5,   320. ,   340.5, 55496. ,    20.5],
       [  324. ,   340.5,   315. ,   330. , 36152. ,    25.5],
       [  344. ,   344. ,   310. ,   315. , 35992. ,    34. ],
       [  306.5,   307. ,   291. ,   305. , 32539. ,    16. ],
       [  305. ,   309. ,   296.5,   309. , 31939. ,    12.5],
       [  313. ,   330. ,   295. ,   304. , 46724. ,    35. ],
       [  302.5,   309. ,   302. ,   306.5, 15698. ,     7. ]])

### <a name='9'></a> Exercise 99
From the array _playway_values_ extract the first 10 rows with the highest volume value sorted in descending order.

In [24]:
# enter solution here
playway_values[playway_values[:,4].argsort()[::-1]][:10]

array([[   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ]])

### <a name='10'></a> Exercise 100
Add to the _playway_values_ array column that will return 1 in case the closing price is higher than the opening price and 0 opposite.

__Expected result:__
```
array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ,      1. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5,      1. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5,      1. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ,      0. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ,      0. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ,      0. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5,      0. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5,      0. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ,      0. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2,      1. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2,      1. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5,      1. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ,      1. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ,      1. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ,      0. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ,      1. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5,      1. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ,      0. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5,      0. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5,      0. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ,      1. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ,      1. ]])
```

In [25]:
# enter solution here
flag = playway_values[:, [0]] < playway_values[:, [3]]
flag = flag.astype(int)

playway_values=np.concatenate((playway_values, flag), axis=1)
playway_values

array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ,      1. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5,      1. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5,      1. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ,      0. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ,      0. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ,      0. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5,      0. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5,      0. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ,      0. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2,      1. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2,      1. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5,      1. ],
       [   264. ,    280. ,    251. ,    270. ,  701